import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/patient/hospitals.module.css";
import { ResearchNavbar } from "../../components/Navbar";
import StudiesCard from "../../components/StudiesCard";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import { useState } from "react";
import AddStudyModal from "../../components/modals/AddStudyModal";

export default function HospitalsVisited() {
  const [addStudyModal, setAddStudyModal] = useState(false);

  return (
    <div className={styles.HospitalsVisited}>
      <Head>
        <title>MEDCOIN | Studies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddStudyModal
        addRecordModal={addStudyModal}
        setAddRecordModal={setAddStudyModal}
      />
      <ResearchNavbar />
      <div className={`container`}>
        <Stack direction={"row"} spacing={2} justifyContent="space-between">
          <div className="page-name">Ongoing Studies</div>
          <Button
            variant="contained"
            color="primary"
            onClick={() => setAddStudyModal(true)}
          >
            Add Study
          </Button>
        </Stack>
        <div className={styles.hospitalsCards}>
          <StudiesCard heading={"Covid19 Study"} />
          <StudiesCard heading={"Schizophrenia Study"} />
        </div>
      </div>
    </div>
  );
}
