import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/patient/request.module.css";
import { HospitalNavbar } from "../../components/Navbar";
import MedicalHistoryCard from "../../components/MedicalHistoryCard";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";

export default function MedicalHistory() {
  return (
    <div className={styles.MedicalHistory}>
      <Head>
        <title>MEDCOIN | Recent Entries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HospitalNavbar />
      <div className={`container`}>
        <Stack direction={"row"} spacing={2} justifyContent="space-between">
          <div className="page-name">Recent Entries</div>
          <Button variant="contained" color="primary">
            Add Record
          </Button>
        </Stack>
        <div className={styles.requestCards}>
          <MedicalHistoryCard />
          <MedicalHistoryCard />
        </div>
      </div>
    </div>
  );
}
