import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/patient/hospitals.module.css";
import Navbar from "../../components/Navbar";
import HospitalsVisitedCard from "../../components/HospitalsVisitedCard";

export default function HospitalsVisited() {
  return (
    <div className={styles.HospitalsVisited}>
      <Head>
        <title>MEDCOIN | HospitalsVisited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={`container`}>
        <div className="page-name">Hospitals Visited</div>
        <div className={styles.hospitalsCards}>
          <HospitalsVisitedCard />
          <HospitalsVisitedCard />
        </div>
      </div>
    </div>
  );
}
