import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/patient/request.module.css";
import Navbar from "../../components/Navbar";
import RequestCard from "../../components/RequestCard";
import { useState } from "react";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";

import GiveAccessModal from "../../components/modals/GiveAccessModal";
import GiveAccessModalRI from "../../components/modals/GiveAccessModalRI";

export default function Requests() {
  const [addStudyModal, setAddStudyModal] = useState(false);
  const [addStudyModalRs, setAddStudyModalRs] = useState(false);

  return (
    <div className={styles.Requests}>
      <Head>
        <title>MEDCOIN | Requests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GiveAccessModal
        addRecordModal={addStudyModal}
        setAddRecordModal={setAddStudyModal}
      />
      <GiveAccessModalRI
        addRecordModal={addStudyModalRs}
        setAddRecordModal={setAddStudyModalRs}
      />
      <Navbar />
      <div className={`container`}>
        <Stack direction={"row"} spacing={2} justifyContent="space-between">
          <div className="page-name">Requests</div>
          <Stack direction={"row"} spacint={2} sx={{ marginRight: "5px" }}>
            <Button
              variant="contained"
              color="primary"
              onClick={() => setAddStudyModal(true)}
            >
              Give Access to a Hospital
            </Button>
            <Button
              variant="contained"
              color="primary"
              onClick={() => setAddStudyModalRs(true)}
            >
              Give Access to a Research Institute
            </Button>
          </Stack>
        </Stack>
        <div className={styles.requestCards}>
          <RequestCard />
          <RequestCard />
        </div>
      </div>
    </div>
  );
}
