import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/patient/request.module.css";
import Navbar from "../../../components/Navbar";
import MedicalHistoryCard from "../../../components/MedicalHistoryCard";

export default function MedicalHistory() {
  return (
    <div className={styles.MedicalHistory}>
      <Head>
        <title>MEDCOIN | Hospital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={`container`}>
        <div className="page-name">Records added by Fortis Hospital</div>
        <div className={styles.requestCards}>
          <MedicalHistoryCard />
          <MedicalHistoryCard />
        </div>
      </div>
    </div>
  );
}
